### ISSUE TITLE
Not navigating to a url

### ISSUE THREAD

**Issue by Den1al** [phimage/Erik#11]
I tried navigating to a url using the:

>  let browser = Erik.visitURL(url) { document, error in
>             print(document)
>         }

snippet, and after testing, the request isn't even made. the only domain i have managed to get was "google.com".
Any help?

**Comment by phimage** [comment]
Could you give me the url?
Is is an https url? If yes did you see in readme about white list on ios

No error?

**Comment by Den1al** [comment]
I have seen the readme regarding App Transport Security, does that feature applies to mac OS X aswell?

**Comment by phimage** [comment]
Only iOS simulator, not mac app
