### ISSUE TITLE
compatibility with carthage

### ISSUE THREAD

**Issue by Jackbt** [phimage/Erik#12]
Is there compatibility with carthage?

**Comment by phimage** [comment]
I have not tested yet but I think I shared the xcode "scheme" (mandatory for carthage)
You can try by putting "phimage/Erik" in your cartfile
Let me now if this work or if you have some errors
(I have no access currently to a mac)

**Comment by Jackbt** [comment]
I tried and there is a build error.

**Comment by phimage** [comment]
could you post it; with --verbose mode maybe

**Comment by phimage** [comment]
project must use carthage by default, not workspace created by pod
