### ISSUE TITLE
LayoutEngine.handleLoadRequestCompletion() does not complete when testing on iOS device

### ISSUE THREAD

**Issue by matadan** [phimage/Erik#15]
It seems that the loading flag is never set on iPhone (running iOS10). I think the while loop does not work as expected on an actual device.

**Comment by phimage** [comment]
thanks for your report
I have plan to change the way to detect end of loading using webkit delegate

did you use swift 3 branch? or master one

**Comment by matadan** [comment]
I’m using cocoapods but I don’t .

I have fixed it I think. But you might have a better way. I observed the “estimatedProgress” property instead of the busy while loop.

**Comment by phimage** [comment]
I will allow to choose the algo via an enum (`loading`, `estimatedProgress`, `navigationDelegate`)

For `estimatedProgress` did you test only if the value `== 1`
_Because if the webview has been never used, and someone try to get content, the value will be `0`_
