### ISSUE TITLE
How to update html ?

### ISSUE THREAD

**Issue by MasterSwift** [phimage/Erik#18]
Are there any sample projects on executive javascript functions and even submitting forms? The example with google search is not working.

**Comment by phimage** [comment]
"The example"? are you talking about unit test?
If yes the code is good, just there is some issues with the parser and google which provide only a part of the full HTML (due to many javascript)

I try to inject HTML ie. full content of a Node using a new proprety "content" using new Kanna feature
https://github.com/tid-kijyun/Kanna/issues/30
but my test is not concluent

**Comment by MasterSwift** [comment]
I am doing a form on a website. After I submit the form using futures , I try to do a link redirect on the future.success method and parse HTML on the new page. But i get the html of the original website with the form. 

`
func verify_portal (email: String, password: String) throws -> () {
   .......
        for (mail, college) in verified_colleges {
            if email.hasSuffix(mail) {
                let portal_url = URL(string:"https://home.cunyfirst.cuny.edu/oam/Portal_Login1.html")!

               let extract_info_url = URL(string: "https://hrsa.cunyfirst.cuny.edu/psc/cnyhcprd/EMPLOYEE/HRMS/c/SA_LEARNER_SERVICES.SSS_STUDENT_CENTER.GBL?FolderPath=PORTAL_ROOT_OBJECT.HC_SSS_STUDENT_CENTER&IsFolder=false&IgnoreParamTempl=FolderPath%2cIsFolder&PortalActualURL=https%3a%2f%2fhrsa.cunyfirst.cuny.edu%2fpsc%2fcnyhcprd%2fEMPLOYEE%2fHRMS%2fc%2fSA_LEARNER_SERVICES.SSS_STUDENT_CENTER.GBL&PortalContentURL=https%3a%2f%2fhrsa.cunyfirst.cuny.edu%2fpsc%2fcnyhcprd%2fEMPLOYEE%2fHRMS%2fc%2fSA_LEARNER_SERVICES.SSS_STUDENT_CENTER.GBL&PortalContentProvider=HRMS&PortalCRefLabel=Student%20Center&PortalRegistryName=EMPLOYEE&PortalServletURI=https%3a%2f%2fhome.cunyfirst.cuny.edu%2fpsp%2fcnyepprd%2f&PortalURI=https%3a%2f%2fhome.cunyfirst.cuny.edu%2fpsc%2fcnyepprd%2f&PortalHostNode=EMPL&NoCrumbs=yes&PortalKeyStruct=yes")!
                let portal_email = email
                let portal_password = password
                // visit
                var future: Future<Document, NSError> = Erik.visitFuture(url: portal_url)
                // fill input field
                future = future.flatMap { document -> Future<Document, NSError> in
                    if let username = document.querySelectorAll("username[name=\"login\"]").first {
                        username["value"] = portal_email
                    }
                    if let password = document.querySelector("password[name='q']") {
                        password["value"] = portal_password
                    }
                    if let form = document.querySelector("form[name=\"submit\"]") as? Form {
                        form.submit()
                    }
                    
                    return Erik.currentContentFuture()
                }

                // finally get final result as success or error
                future.onSuccess { document in
                    // parse result
                    print("logged in")
                    
                    //HOW DO I DO A LINK RE-DIRECT AFTERR SUBMITTING FORM?
                    Erik.visit(url: extract_info_url) { object, error in
                    if let e = error {
               
                    } else if let doc = object {
                    // HTML Inspection
                        
                      
                }
                
            }
            
        }


                    print(document.innerHTML)
                    
                }

                future.onFailure {  error in
                    
                    print("\(error)")
                }

            }
            
        }
        
        
    }

`

**Comment by MasterSwift** [comment]
Im doing a project for my school where I go to my college website, fill a form, submit, open a new url that belongs to the website and then parse table rows. So far, Im having trouble bypassing the form and I want to know how to do mimic web actions (click on links)

`func verify_portal (email: String, password: String) throws -> () {
        ///some code here
       //.....
       
       if email.hasSuffix(".qmail.cuny.edu") {
                let portal_url = URL(string:"https://home.cunyfirst.cuny.edu/oam/Portal_Login1.html")!
                let extract_info_url = URL(string: "https://hrsa.cunyfirst.cuny.edu/psc/cnyhcprd/EMPLOYEE/HRMS/c/SA_LEARNER_SERVICES.SSS_STUDENT_CENTER.GBL?FolderPath=PORTAL_ROOT_OBJECT.HC_SSS_STUDENT_CENTER&IsFolder=false&IgnoreParamTempl=FolderPath%2cIsFolder&PortalActualURL=https%3a%2f%2fhrsa.cunyfirst.cuny.edu%2fpsc%2fcnyhcprd%2fEMPLOYEE%2fHRMS%2fc%2fSA_LEARNER_SERVICES.SSS_STUDENT_CENTER.GBL&PortalContentURL=https%3a%2f%2fhrsa.cunyfirst.cuny.edu%2fpsc%2fcnyhcprd%2fEMPLOYEE%2fHRMS%2fc%2fSA_LEARNER_SERVICES.SSS_STUDENT_CENTER.GBL&PortalContentProvider=HRMS&PortalCRefLabel=Student%20Center&PortalRegistryName=EMPLOYEE&PortalServletURI=https%3a%2f%2fhome.cunyfirst.cuny.edu%2fpsp%2fcnyepprd%2f&PortalURI=https%3a%2f%2fhome.cunyfirst.cuny.edu%2fpsc%2fcnyepprd%2f&PortalHostNode=EMPL&NoCrumbs=yes&PortalKeyStruct=yes")!
                let portal_email = email
                let portal_password = password
                // visit
                var future: Future<Document, NSError> = Erik.visitFuture(url: portal_url)
                // fill input field
                future = future.flatMap { document -> Future<Document, NSError> in
                    if let username = document.querySelectorAll("input[name=\"login\"]").first {
                        username["value"] = portal_email
                        print("username")
                        print(username)
                        print("username")
                    }
                    if let password = document.querySelector("input[name='password']") {
                        password["value"] = portal_password
                        print("password")
                        print(password)
                        print("password")
                    }
                    if let form = document.querySelector("form[name='loginform']") as? Form {
                        form.submit()
                    }
                    
                    return Erik.currentContentFuture()
                }
                // finally get final result as success or error
                future.onSuccess { document in
                    // parse result
                    print("logged in")
                    
                    //VISIT NEW LINK
                    Erik.visit(url: portal_url) { object, error in
                        if let e = error {
                            print(e)
                        } else if let doc = object {
                            // HTML Inspection
                            for tablerow in doc.querySelectorAll("td, .PSLEVEL3GRID") {
                                print(tablerow.elements)
                            
                                
                            }
                            
                        }
                        
                    }

                    
                    //GET HTML OF NEW PAGE
                    
                    //PARSE HTML PAGE
                
                    
                }

                future.onFailure {  error in
                    
                    print("\(error)")
                }
             
            }
            
        
        
        
    }`

**Comment by phimage** [comment]
see https://github.com/phimage/Erik#warning-about-dom-change
you must request a new dom parsing after any modification using currentContent if you want to see if username has been filled

**Comment by MasterSwift** [comment]
I submitted the form but I want to do a re-direct to another link on  that website. after doing form.submit , I tried Erik.current content and then Erik.visit but didnt work. Even if I do Erik.visit after form.submit, it doesnt work. it just brings me to the same page with the login form

**Comment by phimage** [comment]
I update the OSX app, the "test" button fill the google form and then launch submit on the form without any issue

After doing form submit, it's your server which redirect to a page (depending on "action" of form)
If you wait sometime you can get the url.
