### ISSUE TITLE
Carthage and SwiftPM builds fail

### ISSUE THREAD

**Issue by chriseidhof** [phimage/Erik#19]
Hi, 

I tried to install Erik using SwiftPM, but it fails, because BrightFutures doesn't support SwiftPM. Then I tried to install using Carthage, which also fails:

```
The following build commands failed:
    PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/chris/Library/Developer/Xcode/DerivedData/Erik-dgbtbdospwkecwbjmogzqtvhbkvk/Build/Intermediates/Erik.build/Release-iphoneos/Erik.build/Script-BF088855B5DAF2A7EA705BA7.sh
(1 failure)
ld: warning: linking against a dylib which is not safe for use in application extensions: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/XCTest.framework/XCTest.tbd
ld: warning: linking against a dylib which is not safe for use in application extensions: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftXCTest.dylib
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/chris/objc.io/bookkeeping/KDPFetch/Carthage/Checkouts/Erik/Erik.xcworkspace -scheme Erik -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
    PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/chris/Library/Developer/Xcode/DerivedData/Erik-dgbtbdospwkecwbjmogzqtvhbkvk/Build/Intermediates/Erik.build/Release-iphoneos/Erik.build/Script-BF088855B5DAF2A7EA705BA7.sh
(1 failure)
```

**Comment by phimage** [comment]
I fix  #12 yesterday for carthage
I think you try to compil old codes ie. the last tagged version. Please try with head code (github "phimage/Erik" "master")

For SwiftPM I have never tried, and so there is no instruction in readme.
I think BrightFutures is not SwiftPM compliant yet but I can [exclude it](https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md#exclude)

**Comment by phimage** [comment]
BrightFutures is now SPM compatible https://github.com/Thomvis/BrightFutures/blob/master/Package.swift

for carthage,
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2/libxml/HTMLtree.h:15:10: error: 'libxml/xmlversion.h' file not found
<unknown>:0: error: could not build Objective-C module 'libxml2'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/phimage/Dev/TestErikCarthage/Carthage/Checkouts/Erik/Erik.xcworkspace -scheme ErikOSX -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

same as #23 I think

**Comment by phimage** [comment]
carthage is fixed 
tested with latest code github "phimage/Erik" "master"

see Kanna : https://github.com/tid-kijyun/Kanna
`In the project settings add $(SDKROOT)/usr/include/libxml2 to the "header search paths" field`
