### ISSUE TITLE
Threading with promises

### ISSUE THREAD

**Issue by matadan** [phimage/Erik#24]
Hi

I seem to be having issues with promises. Erik.visit() and Erik.visitFuture() take a very long time when embedded in other promises. And then they eventually fail to provide a document  as I think the request is timed out.

I've tried with both BrightFutures and PromiseKit.

Is this possibly a threading issue?

**Comment by phimage** [comment]
There is a timeout in Erik code (`pageLoadTimeout`=20) and some tricky(maybe too much) code to detect end of page loading (`pageLoadedPolicy` )

Some test can be done by editing one or the two attributes attributes `pageLoadedPolicy`, `pageLoadTimeout` of the webkit engine class using this code
```swift
(Erik.sharedInstance.layoutEngine as? WebKitLayoutEngine)?.AN_ATTRIBUTE = VALUE
```

The tree mode, try the last one
- By default `isLoading` attribute of webView is monitored 
- `estimatedProgress` : webView `estimatedProgress` attribute
- and the last one need to use a `navigationDelegate` to detect page loading completion


Maybe two pages loading at same times could have some threading issue.

**Comment by matadan** [comment]
It is definitely timing out as I changed pageLoadTimeout to 60 and it timed out after 1 minute exactly.

I'm not trying to load multiple pages. It just seems that if I wrap up Erik.visit() into a promise something is stalling it.

**Comment by phimage** [comment]
try `pageLoadedPolicy = .navigationDelegate`
I will re-test when I have some time with `BrightFutures`

did you execute in main thread the `visit` instruction ?
just to try, you can dispatch the code into main of background thread

**Comment by matadan** [comment]
It was using .navigationDelegate but I've now got things working. I was trying to create a Future of the page after it had been manipulated.

Here is a working demo function:

```
func demoErikFutures() {
    // Expected console output:
    //    1: Google
    //    -: Microsoft – Official Home Page
    //    2: Microsoft – Official Home Page DOM manipulated
    //    3: Amazon.com
    //    -: How people build software · GitHub
    //    4: How people build software · GitHub DOM manipulated

    func erikPromise(url: URL) -> Future<String, NSError> {
        let promise = Promise<String, NSError>()
        let _ = Erik.visitFuture(url: url).andThen { result in
            switch result {
            case .success(let doc):
                print("-: \(doc.title!)")
                
                // do some things with the DOM
                
                promise.success("\(doc.title!) DOM manipulated")
                
            case .failure(let err):
                print("-: \(err)")
                promise.failure(err)
            }
        }
        
        return promise.future
    }
    
    let urlStrings = [
        "https://www.google.com",
        "https://www.microsoft.com",
        "https://www.amazon.com",
        "https://www.github.com"
    ]
    
    let urls = urlStrings.map { URL(string: $0)! }
    
    Erik.visit(urlString: urlStrings[0]) { doc, err in
        if err == nil {
            print("1: \(doc!.title!)")
        } else {
            print("1: \(err)")
        }
    }
    
    let _ = erikPromise(url: urls[1]).andThen { result in
        switch result {
        case .success(let message):
            print("2: \(message)")
            
        case .failure(let err):
            print("2. \(err)")
        }
    }
    
    let _ = Erik.visitFuture(url: urls[2])
        .andThen { result in
            switch result {
            case .success(let doc):
                print("3: \(doc.title!)")
                
            case .failure(let err):
                print("3: \(err)")
            }
        }.andThen { _ in
            erikPromise(url: urls[3])
                .onSuccess { message in
                    print("4: \(message)")
                }
                .onFailure { err in
                    print("4: \(err)")
                }
        }
}

```

**Comment by matadan** [comment]
I have made a PromiseKit version too:

```
extension Erik {
    public func visitPromise(url: URL) -> Promise<Document> {
        
        return Promise { fulfill, reject in
            let _ = Erik.visit(url: url) { doc, err in
                if err == nil {
                    fulfill(doc!)
                } else {
                    reject(err!)
                }
            }
        }
    }

    public static func visitPromise(url: URL) -> Promise<Document> {
        return Erik.sharedInstance.visitPromise(url: url)
    }
}

func demoErikPromiseKit() {
// Expected output:
//        1: Optional("Google")
//        -: Microsoft – Official Home Page
//        Number of elements: xxx
//        2: Microsoft – Official Home Page DOM manipulated
//        3: Optional("Amazon.com")
//        -: How people build software · GitHub
//        Number of elements: xxx
//        4: How people build software · GitHub DOM manipulated
    
    func manipulateDom(document: Document) {
        print("Number of elements: \(document.elements.count)")
    }
    
    func erikPromise(url: URL) -> Promise<String> {

        let promise: Promise<String> = Erik.visitPromise(url: url)
        .then { doc in
            print("-: \(doc.title!)")

            manipulateDom(document: doc)
            
            return Promise<String>(value: "\(doc.title!) DOM manipulated")
        }
        .catch { err in
            print("-: \(err)")
        }

        return promise
    }
  
    let urlStrings = [
        "https://www.google.com",
        "https://www.microsoft.com",
        "https://www.amazon.com",
        "https://www.github.com"
    ]
    
    let urls = urlStrings.map { URL(string: $0)! }
    
    Erik.visit(urlString: urlStrings[0]) { doc, err in
        if err == nil {
            print("1: \(doc!.title)")
        } else {
            print("1: \(err)")
        }
    }
    
    let _ = erikPromise(url: urls[1])
    .then { message in
        print("2: \(message)")
    }
    .catch { err in
        print("2. \(err)")
    }
    
    let _ = firstly {
        Erik.visitPromise(url: urls[2])
    }
    .then { doc in
        print("3: \(doc.title)")
    }.then {
        erikPromise(url: urls[3])
    }.then { message in
        print("4: \(message)")
    }
    .catch { err in
        print("Error: \(err)")
    }
}

```

**Comment by matadan** [comment]
I've built a project that reproduces the issue I have found. Basically, if you do not put Erik.visit() into the first promise in a chain, it spins and returns .noContent. But if you first call Erik.visit in the first promise in the chain, subsequent Erik.visit calls work properly.

I've made a demo that shows this behaviour using PromiseKit but I think it will be the same with BrightFutures as it seems to be an issue inside Erik that does not play nice with promises.

Would you mind looking at it?

**Comment by matadan** [comment]
As expected. I can recreate with BrightFutures too.

The fix is to call:

`    Erik.visit(url: URL(string: "https://www.google.com")!, completionHandler: nil)
`

before using and Futures or Promises.

**Comment by phimage** [comment]
Thanks for the workaround.

yes I will debug your project to fix the issue, maybe this weekend.
Downloadable archive or github project, as you want

**Comment by matadan** [comment]
I’ve put the demo up on github:

https://github.com/matadan/EriukFutureTest/tree/master/ErikFutureTest <https://github.com/matadan/EriukFutureTest/tree/master/ErikFutureTest>

I’ve tagged 2 versions. One with BrightFutures and one with PromiseKit. I’m using PromiseKit as I prefer the API but I may move to ReactiveSwift one day.

The PromiseKit version also has the “fix’ in it.

For my project, I am visiting www.google.com <http://google.com/> in the initialisation and that seems to prevent the problem with Erik later on.

**Comment by phimage** [comment]
ok, I have found some issue with webkit
My code, which wait on main thread, block webkit page loading. Maybe thread imbrication do not let other thread to consume main thread
Putting this code in new serial queue let webkit do the job

**Comment by matadan** [comment]
As my app becomes more complex, this problem reappears. I don't think my simple hack resolves it for all cases. When do you think you will have a fix ready? Is there anything I can look at to help?

**Comment by phimage** [comment]
I want to do it today but I have some issue with the unit test, and I don't like to commit without testing

like #23 I think there is some issue in my project configuration and Kanna & libxml

**Comment by matadan** [comment]
OK.

Good luck and thanks!

**Comment by matadan** [comment]
On the Kanna page it mentions different ways to install. libxml and include it in the project.

**Comment by phimage** [comment]
testInFuture() unit test added
Queue added to wait on page loading

ps: I have some problem with framework not copied by unit test, also swiftlint issue with FileKit
