### ISSUE TITLE
How to get the response headers? 

### ISSUE THREAD

**Issue by xia0ta0** [phimage/Erik#27]
I am using visit() to crawl a webpage, but how to get the HTTP response headers?

Thanks.

**Comment by phimage** [comment]
I use wkwebview and I think the only way to get headers is to implement the delegate

see https://stackoverflow.com/questions/41128709/retrieve-http-response-headers-from-wkwebview

and to access the internal wkwebview there is cast
```
let engine = Erik.sharedInstance.layoutEngine as? WebKitLayoutEngine
```

**Comment by xia0ta0** [comment]
OK, I got it. Thank you!
