### ISSUE TITLE
Can't install pod properly: "No such module 'Erik'"

### ISSUE THREAD

**Issue by Wiingaard** [phimage/Erik#30]
Hello,

I'm trying to use Erik..
First I tried `pod try Erik` and selected the first demo application, but this gave me the following error:
```
[!] Unable to satisfy the following requirements:

- `FileKit (from `https://github.com/nvzqz/FileKit.git`, branch `develop`)` required by `Podfile`
``` 

Then I tried to install Erik into a new Xcode project (xcode 9, iOS 11). Here's the pod file I used:
```
target 'ErikPlayAgain' do
  use_frameworks!

  pod 'Erik'
end
```
When opening the project I get 22 error, even without `import Erik`. All errors in `Kanna.switf` that look very similar to this: 
`Let 'kDefaultXmlParseOption' is private and cannot be referenced from a default argument value`.
When `import Erik` to my ViewController, I see this: `No such module 'Erik'`.

This is a very trivial task, but I still can't make it work. What am I missing?

**Comment by phimage** [comment]
swift version?
Have you a ".swift-version" file?

Maybe you cut the error message

```
[!] Unable to satisfy the following requirements:

- `FileKit (from `https://github.com/nvzqz/FileKit.git`, branch `develop`)` required by `Podfile`

Specs satisfying the `FileKit (from `https://github.com/nvzqz/FileKit.git`, branch `develop`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by Wiingaard** [comment]
I don't use a `.swift-version`, but I'm using swift 4.. I just added the file, and re-install the cocoa pod, but with the same result.

**Comment by phimage** [comment]
I do not update the project for swift4 yet.

The develop branch of FileKit use swift4

I must update the project and dependencies

**Comment by Wiingaard** [comment]
Okay :) I changed the swift version to 3.2 in both my project and `Erik`and `Kanna`. That did the trick..
Thank you for the very fast response 🥇
