### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by rubenvde** [phimage/Erik#31]
Kanna is in beta right now for Swift 4. Is there a possibility for Erik to start in beta?

**Comment by phimage** [comment]
Yes we can. I will do when I have some time or someone can PR

the kanna issue
https://github.com/tid-kijyun/Kanna/issues/159

**Comment by ahmed-shehata** [comment]
@phimage I have made a PR:
https://github.com/phimage/Erik/pull/32

**Comment by phimage** [comment]
#32 merged in swift4 branch
thanks

**Comment by tid-kijyun** [comment]
I've just released version [4.0.0](https://github.com/tid-kijyun/Kanna/releases/tag/4.0.0) which supports Swift 4.

**Comment by phimage** [comment]
4.0 with swift 4
not pushed yet to cocoapod, but could be used by passing git link lire here
https://github.com/OAuthSwift/OAuthSwift/blob/master/Podfile
