### ISSUE TITLE
Swift 4 not compiling..

### ISSUE THREAD

**Issue by yarodevuci** [phimage/Erik#36]
need few changes

**Comment by phimage** [comment]
xcode version?
swift version?
header of master branch?

When feeling an issue on github please give more information like compilation errors

**Comment by yarodevuci** [comment]
@phimage Sorry about that
Xcode Version 9.3.1 (9E501)
Latest swift version
Branch swift4

**Comment by phimage** [comment]
swift4 branch is a branch when swift4 was in beta

now we are swift 4.1 with some compatibility change when compiling
please use the master head version

**Comment by yarodevuci** [comment]
@phimage 
I tried first with pod 'Erik', and it has issues while compiling
Should I point mast brach to pod?

**Comment by phimage** [comment]
Yes I do not release new version. So you can specify head version by adding
git url in your pod file
