### ISSUE TITLE
How do I access elements in an iframe?

### ISSUE THREAD

**Issue by MasterSwift** [phimage/Erik#37]

**Comment by phimage** [comment]
I never try. Its depend if you could open or not the iframe as new page (there is no redirect in server)
So find your iframe, then take the "src" url and visit it like any page

**Comment by MasterSwift** [comment]
I literally did exactly that 1 minute after posting this lol. Had a bit trouble with "select" html also but I think if I go back, it'll work just fine on the "src" url.
