### ISSUE TITLE
Newboy question

### ISSUE THREAD

**Issue by fghf333** [phimage/Erik#38]
I new at Swift and faced with some errors after adding you framework/library. Can you help me?
xCode: 9.4.1
Cocoapods: 1.5.3
Swift: 3.3/4.1 (both with the same errors)

![Alt text](https://monosnap.com/image/34tQHpFstrM67LT0UV3roHsN0yaHXp)

**Comment by phimage** [comment]
It was version compatibility issue with Kanna. All has been update for xcode 10 now
