### ISSUE TITLE
Change the timeout

### ISSUE THREAD

**Issue by noamalffasy** [phimage/Erik#42]
Hi!

Is it possible to change the timeout on the evaluate JS function?
I'm running a promise in the JS so I need to extend the timeout.

**Comment by phimage** [comment]
Yes you can try

let engine = Erik.sharedInstance.layoutEngine as? WebKitLayoutEngine
engine?.javaScriptWaitTime=60

**Comment by noamalffasy** [comment]
That worked, thanks!
