### ISSUE TITLE
Another Noob Question

### ISSUE THREAD

**Issue by barrymcbride** [phimage/Erik#50]
I'm using XCode 11 and a package.swift file to configure my project. I'd rather keep using this, since it's what I'm familiar with. 

When adding phimage/Erik.git to the package file, I get the following error:

https://github.com/phimage/Erik.git has no Package.swift manifest for version 1.1.1

Is this my error, or something on the Erik side?

**Comment by mesopelagique** [comment]
see release page
https://github.com/phimage/Erik/releases

swift pm is since 5.1.0

**Comment by phimage** [comment]
see release page
https://github.com/phimage/Erik/releases

swift pm is since 5.1.0

**Comment by barrymcbride** [comment]
Thank you, I'm trying to pull in 5.1.0. via package.swift. When I add Erik.git, the package fetching stalls on commoncrypto. When I remove it, everything is fetched and the project built. When I add it back, it stalls fetching IBM-Swift/CommonCrypto. 

Does this make sense to you? I'm working on a web scraping application for my business and need to incorporate a headless browser. Would prefer to use swift so I have the same technology on front-end and back-end.

**Comment by barrymcbride** [comment]
I'm going to open a new issue for package resolution errors with Erik.
