### ISSUE TITLE
Has anybody gotten Erik working on Ubuntu 18?

### ISSUE THREAD

**Issue by mwbelt** [phimage/Erik#53]
Ubuntu 18 can run Swift, has anybody gotten Erik up and running on that Distro?

**Comment by phimage** [comment]
never tested and not marked as compatible

I think there is no webkit
if I am wrong, maybe some if def os(linux) to add...

**Comment by Chidorin** [comment]
there are webkit browsers for linux though🤔 and webkitgtk but not swift based afaik
