### ISSUE TITLE
[Help needed] Running in Vapor project

### ISSUE THREAD

**Issue by advanc3dUA** [phimage/Erik#62]
Hey! I implemented Erik in my Vapor project and it runs well when I do it on my Mac. But I have a problem with the deployment of the project with Erik to my Linux server - the compilation fails with "no such module WebKit". I've done research and found that there is no easy solution to run WebKit on Linux systems. Honestly, I didn't find any workable one. Can you please give me a hint of how can I do it? Such a disaster when everything works that smoothly on Mac and due to one dependency I can't run it on Linux.

**Comment by phimage** [comment]
Hi,

As you can see in readme the project is for macOS(named OSX before) ![Platform](http://img.shields.io/badge/platform-ios_osx-lightgrey.svg?style=flat) only and rely on [WebKit ](https://developer.apple.com/documentation/webkit)(a web framework used natively on this operating system)
I am not sure swift was available on Linux at that time

I think WebKit is available on Linux but maybe not as swift framework (with some extra layer added by apple)

On linux I will use CEF , maybe there is some project that bind it with swift

**Comment by advanc3dUA** [comment]
> 
> I think WebKit is available on Linux but maybe not as swift framework (with some extra layer added by apple)
> 
I found something called webkit2gtk which is hopefully the Linux version of WebKit. I have Installed it, but I have no idea how to give Erik the instruction to use it instead of native WebKit. Is it even possible?
>
> On linux I will use CEF , maybe there is some project that bind it with swift
>
Sounds like a solution. Do you have any ETA planned?

**Comment by phimage** [comment]
Nope, I have no time for that. It's like doing an other project from scratch

Le dim. 12 mai 2024 à 14:09, Yuriy Gudimov ***@***.***> a
écrit :

**Comment by advanc3dUA** [comment]
Thanks a lot for the replies and thanks for the Eric anyway ;)
