### ISSUE TITLE
Typo fix

### ISSUE THREAD

**Issue by jchesne** [phimage/Erik#7]
I dont know yet how to create pull request so here a little typo fix : 

```
let browser = Erik.visitURL(url]) { document, error in
    // browse HTML element, click, submit form and more
}
```

Begin

```
let browser = Erik.visitURL(url) { document, error in
    // browse HTML element, click, submit form and more
}
```

Delete right brackets after url param.

**Comment by phimage** [comment]
For PR two way
- the simple way: go to the file, do edit, github will say that you edit a file that you can write and a fork has been created, juste edit, commit and then a button with create a pull request appear
- the good way for multiple files
  make your fork
  clone it, commit in it, try to make only one commit for each bug fix or feature (you can do into branch)
  then return to github and then you can create pull request between my repo and your fork

**Comment by phimage** [comment]
thanks anyway, I commit fix
