### ISSUE TITLE
Future Plans?

### ISSUE THREAD

**Issue by jmurphyau** [phimage/Erik#8]
Do you have any of the following items as potential tasks for the future of Erik:
- Adding a CLI
- Supporting linux (with swift not going open and working on linux)

These two items will make this a good replacement for phantomjs for CI environments

**Comment by phimage** [comment]
No future plans currently
Could you explain the purpose of a cli? interactive clic to browse web and apply js?

and for swift, maybe one day swift webkit will be released on linux, but I thinks its not possible now

**Comment by catalandres** [comment]
Here's a way you could provide CLI-like functionality: you could deploy code examples in Xcode playgrounds to let users tinker with the framework without having to run a whole project.
